Updates to config
Sharing a few things I had to change to make this example run without errors.

These are the errors I got initially:

```
Call stack:
File ".\mysql_intro.py", line 10, in <module>
'client_flags': [ClientFlag.SSL],
NameError: name 'ClientFlag' is not defined


--------------------
(After resolving line 10)
AttributeError: ssl_key and ssl_cert need to be both specified, or neither.
(This was resolved by renaming this attribute to ssl_ca)
```